#! /bin/sh
total=0
pathsize=`du -s --block-size=1 /home/eemaj/bevans/eecs168/pvjob_vlsi_lib.nand.icv.lvs/run_details | awk '{print $1}'`
total=$(($total+$pathsize))
pathsize=`du -s --block-size=1 /home/eemaj/bevans/eecs168/pvjob_vlsi_lib.nand.icv.lvs/./TOPCELLNAME_err | awk '{print $1}'`
total=$(($total+$pathsize))
pathsize=`du -s --block-size=1 /home/eemaj/bevans/eecs168/pvjob_vlsi_lib.nand.icv.lvs/nand.LAYOUT_ERRORS | awk '{print $1}'`
total=$(($total+$pathsize))
echo $total > /home/eemaj/bevans/eecs168/pvjob_vlsi_lib.nand.icv.lvs/run_details/duse_master.tmp && \
mv /home/eemaj/bevans/eecs168/pvjob_vlsi_lib.nand.icv.lvs/run_details/duse_master.tmp /home/eemaj/bevans/eecs168/pvjob_vlsi_lib.nand.icv.lvs/run_details/duse_master
