set_pns_commit_mode true
# Starting to commit core rings
create_power_straps  -direction vertical  -start_at 47.920 -nets VDD -layer M8 -width 0.480 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 49.760 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 0.720 -nets VDD -layer M8 -width 0.480 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 49.760 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 0.930 -nets VDD -layer M9 -width 0.900 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 48.160 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 49.310 -nets VDD -layer M9 -width 0.900 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 48.160 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 47.200 -nets VSS -layer M8 -width 0.480 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 48.380 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 1.440 -nets VSS -layer M8 -width 0.480 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 48.380 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 2.310 -nets VSS -layer M9 -width 0.900 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 47.440 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 47.930 -nets VSS -layer M9 -width 0.900 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 47.440 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
# Starting to commit block rings
# Starting to commit metal8 straps for net VDD
create_power_straps  -direction vertical  -start_at 3.380 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 1.960 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 49.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 5.180 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 1.960 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 49.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 7.340 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 1.960 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 49.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 9.140 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 1.960 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 49.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 11.300 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 1.960 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 49.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 13.100 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 1.960 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 49.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 15.260 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 1.960 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 49.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 17.060 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 1.960 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 49.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 19.220 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 1.960 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 49.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 21.020 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 1.960 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 49.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 22.820 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 1.960 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 49.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 24.980 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 1.960 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 49.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 26.780 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 1.960 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 49.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 28.940 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 1.960 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 49.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 30.740 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 1.960 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 49.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 32.900 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 1.960 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 49.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 34.700 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 1.960 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 49.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 36.860 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 1.960 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 49.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 38.660 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 1.960 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 49.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 40.460 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 1.960 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 49.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 42.620 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 1.960 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 49.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 44.420 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 1.960 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 49.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal8 straps for net VSS
create_power_straps  -direction vertical  -start_at 3.860 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 1.960 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 48.380 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 5.660 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 1.960 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 48.380 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 7.820 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 1.960 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 48.380 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 9.620 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 1.960 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 48.380 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 11.780 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 1.960 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 48.380 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 13.580 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 1.960 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 48.380 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 15.740 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 1.960 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 48.380 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 17.540 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 1.960 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 48.380 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 19.700 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 1.960 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 48.380 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 21.500 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 1.960 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 48.380 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 23.300 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 1.960 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 48.380 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 25.460 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 1.960 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 48.380 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 27.260 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 1.960 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 48.380 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 29.420 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 1.960 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 48.380 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 31.220 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 1.960 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 48.380 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 33.380 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 1.960 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 48.380 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 35.180 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 1.960 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 48.380 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 37.340 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 1.960 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 48.380 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 39.140 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 1.960 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 48.380 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 40.940 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 1.960 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 48.380 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 43.100 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 1.960 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 48.380 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 44.900 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 1.960 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 48.380 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal9 straps for net VDD
create_power_straps  -direction horizontal  -start_at 5.035 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 2.630 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 48.160 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 7.535 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 2.630 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 48.160 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 10.035 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 2.630 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 48.160 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 12.535 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 2.630 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 48.160 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 15.535 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 2.630 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 48.160 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 18.035 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 2.630 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 48.160 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 20.535 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 2.630 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 48.160 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 23.535 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 2.630 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 48.160 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 26.035 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 2.630 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 48.160 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 28.535 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 2.630 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 48.160 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 31.035 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 2.630 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 48.160 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 34.035 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 2.630 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 48.160 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 36.535 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 2.630 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 48.160 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 39.035 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 2.630 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 48.160 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 41.535 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 2.630 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 48.160 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 44.535 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 2.630 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 48.160 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal9 straps for net VSS
create_power_straps  -direction horizontal  -start_at 5.965 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 2.630 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 47.440 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 8.465 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 2.630 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 47.440 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 10.965 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 2.630 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 47.440 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 13.465 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 2.630 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 47.440 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 16.465 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 2.630 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 47.440 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 18.965 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 2.630 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 47.440 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 21.465 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 2.630 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 47.440 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 24.465 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 2.630 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 47.440 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 26.965 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 2.630 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 47.440 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 29.465 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 2.630 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 47.440 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 31.965 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 2.630 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 47.440 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 34.965 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 2.630 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 47.440 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 37.465 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 2.630 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 47.440 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 39.965 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 2.630 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 47.440 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 42.465 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 2.630 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 47.440 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 45.465 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 2.630 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 47.440 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
set_pns_commit_mode false
