set_pns_commit_mode true
# Starting to commit core rings
create_power_straps  -direction horizontal  -start_at 0.690 -nets VDD -layer M8 -width 0.320 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 137.070 -nets VDD -layer M8 -width 0.320 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 136.710 -nets VDD -layer M9 -width 1.040 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 1.050 -nets VDD -layer M9 -width 1.040 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 1.200 -nets VSS -layer M8 -width 0.320 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 135.660 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 136.560 -nets VSS -layer M8 -width 0.320 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 135.660 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 135.140 -nets VSS -layer M9 -width 1.040 -start_low_ends coordinate  -start_low_ends_coordinate 1.040 -start_high_ends coordinate  -start_high_ends_coordinate 136.720 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 2.620 -nets VSS -layer M9 -width 1.040 -start_low_ends coordinate  -start_low_ends_coordinate 1.040 -start_high_ends coordinate  -start_high_ends_coordinate 136.720 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
# Starting to commit block rings
# Starting to commit metal8 straps for net VDD
create_power_straps  -direction horizontal  -start_at 5.320 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 9.820 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 14.320 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 18.320 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 22.820 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 27.320 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 31.820 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 35.820 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 40.320 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 44.820 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 48.820 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 53.320 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 57.820 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 61.820 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 66.320 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 70.820 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 75.320 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 79.320 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 83.820 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 88.320 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 92.320 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 96.820 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 101.320 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 105.320 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 109.820 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 114.320 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 118.820 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 122.820 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 127.320 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 131.820 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal8 straps for net VSS
create_power_straps  -direction horizontal  -start_at 5.680 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 135.660 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 10.180 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 135.660 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 14.680 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 135.660 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 18.680 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 135.660 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 23.180 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 135.660 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 27.680 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 135.660 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 32.180 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 135.660 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 36.180 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 135.660 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 40.680 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 135.660 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 45.180 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 135.660 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 49.180 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 135.660 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 53.680 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 135.660 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 58.180 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 135.660 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 62.180 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 135.660 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 66.680 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 135.660 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 71.180 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 135.660 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 75.680 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 135.660 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 79.680 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 135.660 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 84.180 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 135.660 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 88.680 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 135.660 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 92.680 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 135.660 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 97.180 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 135.660 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 101.680 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 135.660 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 105.680 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 135.660 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 110.180 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 135.660 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 114.680 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 135.660 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 119.180 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 135.660 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 123.180 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 135.660 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 127.680 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 135.660 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 132.180 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 4.350 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 135.660 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal9 straps for net VDD
create_power_straps  -direction vertical  -start_at 9.840 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 6.920 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 16.380 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 6.920 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 22.930 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 6.920 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 30.410 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 6.920 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 36.950 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 6.920 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 44.430 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 6.920 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 50.980 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 6.920 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 57.520 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 6.920 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 65.000 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 6.920 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 71.550 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 6.920 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 79.030 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 6.920 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 85.570 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 6.920 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 92.120 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 6.920 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 99.600 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 6.920 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 106.140 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 6.920 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 113.620 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 6.920 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 120.170 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 6.920 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 126.710 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 6.920 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 137.230 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal9 straps for net VSS
create_power_straps  -direction vertical  -start_at 10.890 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 6.920 -start_low_ends coordinate  -start_low_ends_coordinate 1.040 -start_high_ends coordinate  -start_high_ends_coordinate 136.720 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 17.440 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 6.920 -start_low_ends coordinate  -start_low_ends_coordinate 1.040 -start_high_ends coordinate  -start_high_ends_coordinate 136.720 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 23.980 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 6.920 -start_low_ends coordinate  -start_low_ends_coordinate 1.040 -start_high_ends coordinate  -start_high_ends_coordinate 136.720 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 31.460 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 6.920 -start_low_ends coordinate  -start_low_ends_coordinate 1.040 -start_high_ends coordinate  -start_high_ends_coordinate 136.720 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 38.010 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 6.920 -start_low_ends coordinate  -start_low_ends_coordinate 1.040 -start_high_ends coordinate  -start_high_ends_coordinate 136.720 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 45.490 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 6.920 -start_low_ends coordinate  -start_low_ends_coordinate 1.040 -start_high_ends coordinate  -start_high_ends_coordinate 136.720 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 52.030 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 6.920 -start_low_ends coordinate  -start_low_ends_coordinate 1.040 -start_high_ends coordinate  -start_high_ends_coordinate 136.720 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 58.580 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 6.920 -start_low_ends coordinate  -start_low_ends_coordinate 1.040 -start_high_ends coordinate  -start_high_ends_coordinate 136.720 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 66.060 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 6.920 -start_low_ends coordinate  -start_low_ends_coordinate 1.040 -start_high_ends coordinate  -start_high_ends_coordinate 136.720 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 72.600 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 6.920 -start_low_ends coordinate  -start_low_ends_coordinate 1.040 -start_high_ends coordinate  -start_high_ends_coordinate 136.720 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 80.080 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 6.920 -start_low_ends coordinate  -start_low_ends_coordinate 1.040 -start_high_ends coordinate  -start_high_ends_coordinate 136.720 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 86.630 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 6.920 -start_low_ends coordinate  -start_low_ends_coordinate 1.040 -start_high_ends coordinate  -start_high_ends_coordinate 136.720 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 93.170 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 6.920 -start_low_ends coordinate  -start_low_ends_coordinate 1.040 -start_high_ends coordinate  -start_high_ends_coordinate 136.720 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 100.650 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 6.920 -start_low_ends coordinate  -start_low_ends_coordinate 1.040 -start_high_ends coordinate  -start_high_ends_coordinate 136.720 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 107.200 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 6.920 -start_low_ends coordinate  -start_low_ends_coordinate 1.040 -start_high_ends coordinate  -start_high_ends_coordinate 136.720 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 114.680 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 6.920 -start_low_ends coordinate  -start_low_ends_coordinate 1.040 -start_high_ends coordinate  -start_high_ends_coordinate 136.720 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 121.220 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 6.920 -start_low_ends coordinate  -start_low_ends_coordinate 1.040 -start_high_ends coordinate  -start_high_ends_coordinate 136.720 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 127.770 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 6.920 -start_low_ends coordinate  -start_low_ends_coordinate 1.040 -start_high_ends coordinate  -start_high_ends_coordinate 136.720 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
set_pns_commit_mode false
